import type { NextPage } from "next";
import Head from "next/head";
import ChatContent from "../components/ChatContent";
import Chats from "../components/Chats";
import Settings from "../components/Settings";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Settings />
      <Chats />
      <ChatContent />
    </div>
  );
};

export default Home;
